/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as EventTypesRouteImport } from './routes/event-types'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EventsIndexRouteImport } from './routes/events.index'
import { Route as AttendeesIndexRouteImport } from './routes/attendees.index'
import { Route as EventsTestRouteImport } from './routes/events.test'
import { Route as EventsSundayServiceRouteImport } from './routes/events.sunday-service'
import { Route as EventsNewRouteImport } from './routes/events.new'
import { Route as EventsHistoryRouteImport } from './routes/events.history'
import { Route as EventsArchiveRouteImport } from './routes/events.archive'
import { Route as EventsSlugRouteImport } from './routes/events.$slug'
import { Route as EventsIdRouteImport } from './routes/events.$id'
import { Route as AttendeesNewRouteImport } from './routes/attendees.new'
import { Route as AttendeesIdRouteImport } from './routes/attendees.$id'
import { Route as AttendeesIdIndexRouteImport } from './routes/attendees.$id.index'
import { Route as AttendeesIdEditRouteImport } from './routes/attendees.$id.edit'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const EventTypesRoute = EventTypesRouteImport.update({
  id: '/event-types',
  path: '/event-types',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsIndexRoute = EventsIndexRouteImport.update({
  id: '/events/',
  path: '/events/',
  getParentRoute: () => rootRouteImport,
} as any)
const AttendeesIndexRoute = AttendeesIndexRouteImport.update({
  id: '/attendees/',
  path: '/attendees/',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsTestRoute = EventsTestRouteImport.update({
  id: '/events/test',
  path: '/events/test',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsSundayServiceRoute = EventsSundayServiceRouteImport.update({
  id: '/events/sunday-service',
  path: '/events/sunday-service',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsNewRoute = EventsNewRouteImport.update({
  id: '/events/new',
  path: '/events/new',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsHistoryRoute = EventsHistoryRouteImport.update({
  id: '/events/history',
  path: '/events/history',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsArchiveRoute = EventsArchiveRouteImport.update({
  id: '/events/archive',
  path: '/events/archive',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsSlugRoute = EventsSlugRouteImport.update({
  id: '/events/$slug',
  path: '/events/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsIdRoute = EventsIdRouteImport.update({
  id: '/events/$id',
  path: '/events/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AttendeesNewRoute = AttendeesNewRouteImport.update({
  id: '/attendees/new',
  path: '/attendees/new',
  getParentRoute: () => rootRouteImport,
} as any)
const AttendeesIdRoute = AttendeesIdRouteImport.update({
  id: '/attendees/$id',
  path: '/attendees/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AttendeesIdIndexRoute = AttendeesIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AttendeesIdRoute,
} as any)
const AttendeesIdEditRoute = AttendeesIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => AttendeesIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/event-types': typeof EventTypesRoute
  '/login': typeof LoginRoute
  '/attendees/$id': typeof AttendeesIdRouteWithChildren
  '/attendees/new': typeof AttendeesNewRoute
  '/events/$id': typeof EventsIdRoute
  '/events/$slug': typeof EventsSlugRoute
  '/events/archive': typeof EventsArchiveRoute
  '/events/history': typeof EventsHistoryRoute
  '/events/new': typeof EventsNewRoute
  '/events/sunday-service': typeof EventsSundayServiceRoute
  '/events/test': typeof EventsTestRoute
  '/attendees/': typeof AttendeesIndexRoute
  '/events/': typeof EventsIndexRoute
  '/attendees/$id/edit': typeof AttendeesIdEditRoute
  '/attendees/$id/': typeof AttendeesIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/event-types': typeof EventTypesRoute
  '/login': typeof LoginRoute
  '/attendees/new': typeof AttendeesNewRoute
  '/events/$id': typeof EventsIdRoute
  '/events/$slug': typeof EventsSlugRoute
  '/events/archive': typeof EventsArchiveRoute
  '/events/history': typeof EventsHistoryRoute
  '/events/new': typeof EventsNewRoute
  '/events/sunday-service': typeof EventsSundayServiceRoute
  '/events/test': typeof EventsTestRoute
  '/attendees': typeof AttendeesIndexRoute
  '/events': typeof EventsIndexRoute
  '/attendees/$id/edit': typeof AttendeesIdEditRoute
  '/attendees/$id': typeof AttendeesIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/event-types': typeof EventTypesRoute
  '/login': typeof LoginRoute
  '/attendees/$id': typeof AttendeesIdRouteWithChildren
  '/attendees/new': typeof AttendeesNewRoute
  '/events/$id': typeof EventsIdRoute
  '/events/$slug': typeof EventsSlugRoute
  '/events/archive': typeof EventsArchiveRoute
  '/events/history': typeof EventsHistoryRoute
  '/events/new': typeof EventsNewRoute
  '/events/sunday-service': typeof EventsSundayServiceRoute
  '/events/test': typeof EventsTestRoute
  '/attendees/': typeof AttendeesIndexRoute
  '/events/': typeof EventsIndexRoute
  '/attendees/$id/edit': typeof AttendeesIdEditRoute
  '/attendees/$id/': typeof AttendeesIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/event-types'
    | '/login'
    | '/attendees/$id'
    | '/attendees/new'
    | '/events/$id'
    | '/events/$slug'
    | '/events/archive'
    | '/events/history'
    | '/events/new'
    | '/events/sunday-service'
    | '/events/test'
    | '/attendees/'
    | '/events/'
    | '/attendees/$id/edit'
    | '/attendees/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/event-types'
    | '/login'
    | '/attendees/new'
    | '/events/$id'
    | '/events/$slug'
    | '/events/archive'
    | '/events/history'
    | '/events/new'
    | '/events/sunday-service'
    | '/events/test'
    | '/attendees'
    | '/events'
    | '/attendees/$id/edit'
    | '/attendees/$id'
  id:
    | '__root__'
    | '/'
    | '/event-types'
    | '/login'
    | '/attendees/$id'
    | '/attendees/new'
    | '/events/$id'
    | '/events/$slug'
    | '/events/archive'
    | '/events/history'
    | '/events/new'
    | '/events/sunday-service'
    | '/events/test'
    | '/attendees/'
    | '/events/'
    | '/attendees/$id/edit'
    | '/attendees/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EventTypesRoute: typeof EventTypesRoute
  LoginRoute: typeof LoginRoute
  AttendeesIdRoute: typeof AttendeesIdRouteWithChildren
  AttendeesNewRoute: typeof AttendeesNewRoute
  EventsIdRoute: typeof EventsIdRoute
  EventsSlugRoute: typeof EventsSlugRoute
  EventsArchiveRoute: typeof EventsArchiveRoute
  EventsHistoryRoute: typeof EventsHistoryRoute
  EventsNewRoute: typeof EventsNewRoute
  EventsSundayServiceRoute: typeof EventsSundayServiceRoute
  EventsTestRoute: typeof EventsTestRoute
  AttendeesIndexRoute: typeof AttendeesIndexRoute
  EventsIndexRoute: typeof EventsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/event-types': {
      id: '/event-types'
      path: '/event-types'
      fullPath: '/event-types'
      preLoaderRoute: typeof EventTypesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/': {
      id: '/events/'
      path: '/events'
      fullPath: '/events/'
      preLoaderRoute: typeof EventsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/attendees/': {
      id: '/attendees/'
      path: '/attendees'
      fullPath: '/attendees/'
      preLoaderRoute: typeof AttendeesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/test': {
      id: '/events/test'
      path: '/events/test'
      fullPath: '/events/test'
      preLoaderRoute: typeof EventsTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/sunday-service': {
      id: '/events/sunday-service'
      path: '/events/sunday-service'
      fullPath: '/events/sunday-service'
      preLoaderRoute: typeof EventsSundayServiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/new': {
      id: '/events/new'
      path: '/events/new'
      fullPath: '/events/new'
      preLoaderRoute: typeof EventsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/history': {
      id: '/events/history'
      path: '/events/history'
      fullPath: '/events/history'
      preLoaderRoute: typeof EventsHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/archive': {
      id: '/events/archive'
      path: '/events/archive'
      fullPath: '/events/archive'
      preLoaderRoute: typeof EventsArchiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/$slug': {
      id: '/events/$slug'
      path: '/events/$slug'
      fullPath: '/events/$slug'
      preLoaderRoute: typeof EventsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/$id': {
      id: '/events/$id'
      path: '/events/$id'
      fullPath: '/events/$id'
      preLoaderRoute: typeof EventsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/attendees/new': {
      id: '/attendees/new'
      path: '/attendees/new'
      fullPath: '/attendees/new'
      preLoaderRoute: typeof AttendeesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/attendees/$id': {
      id: '/attendees/$id'
      path: '/attendees/$id'
      fullPath: '/attendees/$id'
      preLoaderRoute: typeof AttendeesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/attendees/$id/': {
      id: '/attendees/$id/'
      path: '/'
      fullPath: '/attendees/$id/'
      preLoaderRoute: typeof AttendeesIdIndexRouteImport
      parentRoute: typeof AttendeesIdRoute
    }
    '/attendees/$id/edit': {
      id: '/attendees/$id/edit'
      path: '/edit'
      fullPath: '/attendees/$id/edit'
      preLoaderRoute: typeof AttendeesIdEditRouteImport
      parentRoute: typeof AttendeesIdRoute
    }
  }
}

interface AttendeesIdRouteChildren {
  AttendeesIdEditRoute: typeof AttendeesIdEditRoute
  AttendeesIdIndexRoute: typeof AttendeesIdIndexRoute
}

const AttendeesIdRouteChildren: AttendeesIdRouteChildren = {
  AttendeesIdEditRoute: AttendeesIdEditRoute,
  AttendeesIdIndexRoute: AttendeesIdIndexRoute,
}

const AttendeesIdRouteWithChildren = AttendeesIdRoute._addFileChildren(
  AttendeesIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EventTypesRoute: EventTypesRoute,
  LoginRoute: LoginRoute,
  AttendeesIdRoute: AttendeesIdRouteWithChildren,
  AttendeesNewRoute: AttendeesNewRoute,
  EventsIdRoute: EventsIdRoute,
  EventsSlugRoute: EventsSlugRoute,
  EventsArchiveRoute: EventsArchiveRoute,
  EventsHistoryRoute: EventsHistoryRoute,
  EventsNewRoute: EventsNewRoute,
  EventsSundayServiceRoute: EventsSundayServiceRoute,
  EventsTestRoute: EventsTestRoute,
  AttendeesIndexRoute: AttendeesIndexRoute,
  EventsIndexRoute: EventsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
